#!/bin/sh
#
# This is an example hook. It synchronizes calcurse with a CalDAV server before
# saving the data files.
#
# In order to install this hook, copy this file to
# $XDG_CONFIG_HOME/calcurse/hooks/ (~/.config/calcurse/hooks/) or
# ~/.calcurse/hooks/ if using ~/.calcurse.

# [ -d "$HOME/.config/calcurse" ] && data_dir="${XDG_DATA_HOME:-$HOME/.local/share}/calcurse"

# cd "$data_dir" || exit

# # Do not do anything when synchronizing with a CalDAV server.
# [ -f caldav/lock ] && exit

# # Run the CalDAV synchronization script in the background.
# if [ -d caldav ] && command -v CALCURSE_CALDAV_PASSWORD=$(security
# find-internet-password -s 'mail.mailo.com' -w) calcurse-caldav >/dev/null; then (
# 		date="$(date +'%b %d %H:%M:%S')"
# 		echo "$date Running calcurse-caldav from the pre-load hook..."
# 		CALCURSE_CALDAV_PASSWORD=$(security find-internet-password -s 'mail.mailo.com' -w) calcurse-caldav ### <- There was an issue here, found it!
# 	) >>caldav/log 2>&1 &
#         notify-send -u low 'Calcurse synchronized with server'
# fi
