#!/usr/bin/env sh

~/Documents/build/limelight/bin/limelight -m config width            3
~/Documents/build/limelight/bin/limelight -m config radius           0
~/Documents/build/limelight/bin/limelight -m config placement        interior
~/Documents/build/limelight/bin/limelight -m config active_color     0x99ff720C
~/Documents/build/limelight/bin/limelight -m config normal_color     0xff505050

echo "limelight configuration loaded.."
