#!/usr/bin/env sh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m rule --add app="^Préférences Système$" manage=off grid=4:4:1:1:2:2 
yabai -m rule --add app="^Finder$" manage=off 
yabai -m rule --add app="^AppCleaner$" manage=off grid=4:4:1:1:2:2 
yabai -m rule --add app="^Alfred Preferences$" manage=off grid=4:4:1:1:2:2 
yabai -m rule --add app="^Karabiner-Elements$" manage=off grid=4:4:1:1:2:2 
yabai -m rule --add app="^rMview.json$" manage=off
yabai -m rule --add app="mpv" manage=off grid=4:4:1:1:2:2 
# yabai -m rule --add app="kitty" manage=off grid=4:4:1:1:2:2 
yabai -m rule --add app="^TV$" manage=off grid=4:4:1:1:2:2 
yabai -m rule --add app="Band-in-a-box" manage=off
yabai -m rule --add app="^Soduto Browser$" manage=off
yabai -m rule --add title="Journal" manage=off grid=4:4:1:1:2:2 
yabai -m rule --add title="Float" manage=off grid=4:4:1:1:2:2
yabai -m rule --add title="mpv" manage=off layer=above grid=4:4:1:1:2:2
yabai -m rule --add title="Mini" manage=off grid=6:6:2:2:2:2
yabai -m rule --add app="LaCinetek" native-fullscreen=on
yabai -m rule --add app="^GIMP" manage=off
yabai -m rule --add app="^Utilitaire" manage=off grid=6:6:2:2:2:2
# yabai -m rule --add app="^Logic Pro X$" manage=off
# yabai -m signal --add event=window_created title="^Float$" action 'yabai -m window $YABAI_WINDOW_ID --toggle float'
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus first "
# yabai -m signal --add event=window_focused app="^Logic Pro X$" action="yabai -m window --toggle float"

# yabai -m signal --add event=application_launched app="^zathura$" \
# 	action="yabai -m window --focus next || yabai -m window --focus last" # ok ça marche mais c'est moche
	# action="yabai -m window --focus "

# yabai -m signal --add event=window_destroyed app="Chromium" \
# 	action="yabai -m window --focus recent || yabai -m window --focus last" # ok ça marche mais c'est moche

# found here : https://github.com/koekeishiya/yabai/issues/1012
# yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus recent || yabai -m window --focus first"


# bar settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          on
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
# yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                off
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_color   0x99ff720C
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config insert_feedback_color 	     0x99ff720C
# yabai -m config active_window_opacity        1.0
# yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   5

# spacebar
yabai -m config external_bar all:0:0

# restore position of floating windows when they are manually unfloated
# ~/Documents/Scripts/yabai_restore.sh
# # Create temp dir to restore widows when float and unfloat (https://github.com/koekeishiya/yabai/issues/681)
# tempDir=/tmp/yabai-tiling-floating-toggle
# [ -d $tempDir ] && rm -rf $tempDir
# mkdir $tempDir

# Per-space
# yabai -m config --space 5 auto_balance off
# yabai -m config --space 1 split_ratio 0.2

# echo "yabai configuration loaded.."

# Auto update
# YABAI_CERT=yabai-cert sh -c "$(curl -fsSL "https://git.io/update-yabai")" &

killall limelight &> /dev/null
~/Documents/Scripts/limelight/limelight/bin/limelight -c ~/.config/limelight/limelightrc & /dev/null &
